version: "3"
services:
  wordpress:
    image: wordpress:6.2.2-php8.0-fpm
    volumes:
      - ./wordpress/:/var/www/html
    ports:
      - "9000:9000"
    container_name: wordpress
    depends_on:
      - db
  nginx:
    image: nginx:latest
    container_name: server
    volumes:
      - ./wordpress/:/var/www/html
      - ./nginx/nginx.conf/:/etc/nginx/nginx.conf
      - ./nginx/logs/:/var/log/nginx
      - ./etc/letsencrypt:/etc/letsencrypt
    ports:
      - "150:80"
    depends_on:
      - wordpress
  certbot:
    image: certbot/certbot
    depends_on:
      - nginx
    container_name: certbot
    volumes:
      - ./etc/letsencrypt:/etc/letsencrypt
      - ./wordpress/:/var/www/html
    # command: certonly --webroot --webroot-path=/var/www/html --email pavlenko.at@mail.ru --agree-tos --no-eff-email -d cosmos-prosto.space
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    container_name: db
    volumes:
      - ./mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8083:80"
    environment:
      PMA_HOST: db
    container_name: admin
