version: "3"
services:
  wordpress:
    image: wordpress:6.2.2-php8.0-fpm
    volumes:
      - ./wordpress/:/var/www/html
    ports:
      - 8000:9000
    container_name: wordpress
  certbot:
    image: certbot/certbot
    volumes:
      - /path/to/certbot/config:/etc/letsencrypt
      - /path/to/certbot/certs:/etc/letsencrypt/archive
      - /wordpress:/var/www/html
    command: certonly --webroot --webroot-path /var/www/html --email aleksander.freelancer@gmail.com --agree-tos --no-eff-email --force-renewal -d cosmos-prosto.space
  nginx:
    image: nginx:latest
    container_name: server
    volumes:
      - ./wordpress/:/var/www/html
      - ./nginx/nginx.conf/:/etc/nginx/nginx.conf
      - ./nginx/logs/:/var/log/nginx
      - ./certbot/certs:/etc/nginx/ssl:ro
    ports:
      - 150:120
      - 443:443
    depends_on:
      - wordpress
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 4000:3306
    container_name: db
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - default
    command: --default-authentication-plugin=mysql_native_password
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8080:80"
    networks:
      - default
    environment:
      PMA_HOST: db
    container_name: admin

networks:
  default:
    driver: bridge
